name: Build Apps

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_ios:
    runs-on: ubuntu-latest

    steps:
      - name: Build iOS on Appflow
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.APPFLOW_TOKEN }}
          app-id: 9f0851ec
          platform: iOS
          build-type: app-store
          certificate: Distribution
          build-stack: macOS - 2023.03
          destinations: Voyager App Store
          upload-artifact: iOS-Build.zip

  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Build Android on Appflow
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.APPFLOW_TOKEN }}
          app-id: 9f0851ec
          platform: Android
          build-type: release
          certificate: Voyager Play Store
          destinations: Voyager Play Store
          upload-artifact: Android-Build.zip
