name: Fly Deploy
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: 🚀 Fly Deploy
        run: flyctl deploy --remote-only -a $FLY_APP
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP: ${{ secrets.FLY_APP }}
          FLY_REGION: ${{ secrets.FLY_REGION }}
      - name: 🔃 Sync Tags
        run: |
          git remote add upstream https://github.com/aeharding/voyager.git
          git fetch upstream
          git push --tags
